---
# Download and apply manifest
- name: Creates directory
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0775

- name: Download metrics-server manifest to the cluster.
  ansible.builtin.get_url:
    url: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
    dest: "{{ tmp_dir }}/metrics-server.yaml"
    mode: '0664'

- name: Apply metrics-server manifest to the cluster.
  kubernetes.core.k8s:
    state: present
    src: "{{ tmp_dir }}/metrics-server.yaml"
    kubeconfig: "{{ kubeconfig }}"