---
# tasks file for konveyor
- name: Creates directory
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0775

- name: Download konveyor/tackle2-operator/main/tackle-k8s.yaml 
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/konveyor/tackle2-operator/main/tackle-k8s.yaml
    dest: "{{ tmp_dir }}/tackle-k8s.yaml"
    mode: '0664'

- name: Apply tackle-k8s.yaml to the cluster.
  kubernetes.core.k8s:
    state: present
    src: "{{ tmp_dir }}/tackle-k8s.yaml"
    kubeconfig: "{{ kubeconfig }}"

- name: Wait for Tackle CRD to be established
  kubernetes.core.k8s:
    definition:
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: "{{ item }}"
    wait: yes
    wait_condition:
      type: Established
      status: True
      reason: InitialNamesAccepted
  loop:
    - tackles.tackle.konveyor.io
  register: result
  until: result is succeeded
  retries: 20
  delay: 5

- name: Apply a Tackle manifest to the cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    definition: 
      apiVersion: tackle.konveyor.io/v1alpha1
      kind: Tackle
      metadata:
        name: "tackle"
        namespace: konveyor-tackle 
      spec:
        rwx_supported: "false"
        feature_auth_required: "false"
    state: present
